### ISSUE TITLE
Initiative needs a champion

### ISSUE THREAD

**Issue by Trott** [nodejs/build-toolchain-next#13]
There is no champion for the strategic initiative around next-gen toolchain for Node.js. (It was @mmarchini, but she is stepping away from the project for a while.) This could use a champion. @nodejs/tsc @nodejs/build 

Refs: https://github.com/nodejs/node/pull/42750

Adding a `tsc-agenda` label to see if anyone is interested or has ideas for who might be a good person to pick it up. But it can be removed if there is discussion and no candidate emerges.

**Comment by mhdawson** [comment]
Tweet went out after last TSC meeting thanks @joyeecheung, but still not volunteer to be the champion.

**Comment by mhdawson** [comment]
We agreed to remove the initiative for now from the list since we've not had a volunteer to champion.

I looked after the meeting and Mary already moved it when she moved to emeritus so there is nothing to do. 

Going to close this issue. If we get a champion we can re-add/re-start the initiative.

**Comment by nschonni** [comment]
Not sure if https://github.com/nodejs/build-toolchain-next/issues/11 should get closed too. Not sure if it got posted on hacker news or something, but there has been a bunch of comments there in the last week of people saying their intersted, but it's probably a moot point without a champion

**Comment by RaisinTen** [comment]
Yes, it got posted on twitter in https://twitter.com/nodejs/status/1520176973984591872. I would be +1 about closing if there are no objections because forming a team probably wouldn't help if we don't have a champion.
